org.gradle.jvmargs=-Xmx1400m -XX:MaxMetaspaceSize=480m -Dfile.encoding=UTF-8
org.gradle.workers.max=1
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=false
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.jvmargs=-Xmx420m
kotlin.incremental=false
android.useAndroidX=true
android.nonTransitiveRClass=true
android.r8.useFullClasspathForDexingTransform=true
